name: Trigger auto deployment for poc-fastapi-container

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/poc-fastapi-container-AutoDeployTrigger-9fd380e2-8af1-4f80-8eb0-8b9648b822bd.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.POCFASTAPICONTAINER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.POCFASTAPICONTAINER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.POCFASTAPICONTAINER_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: poc4containerregistery.azurecr.io
          registryUsername: ${{ secrets.POCFASTAPICONTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.POCFASTAPICONTAINER_REGISTRY_PASSWORD }}
          containerAppName: poc-fastapi-container
          resourceGroup: DefaultResourceGroup-SEC
          imageToBuild: poc4containerregistery.azurecr.io/poc-fastapi-container:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


